# Service Info
spring:

  application.name: SpringRessourceProcessor

  messages:
      basename: message
      cache-seconds: -1
      encoding: UTF-8

  data.rest:
      return-body-on-update : true
      return-body-on-create : true

  datasource:
    url: jdbc:h2:mem:service_data
    username: sa
    password:

  jpa:
    properties.hibernate.search.default:
        directory_provider : filesystem
        indexBase : /tmp/srp
    database: H2
    hibernate:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: create-drop

server.port: 8080